[package]
name = "rgb20-token"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "my_program"
path = "src/main.rs"

[lib]
name = "custom_schema"
path = "src/custom_schema.rs"

[dependencies]
rgb-std = { version = "0.10.8", features = ["serde", "fs"] }
serde = "1.0.152"
serde_json = "1.0.93"
